In [1]:
import numpy as np  # importing numpy

In [2]:
arr = np.arange(0,11)  # creating a array

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr+5 #  take every element and add 5 to each( elemnen by element)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr -2 #  subtact 2 from every element

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
arr + arr  # shape of array must be same 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arr /arr # here  0/number we dont get any number , we get placed holder of nan (not a number)

C:\Users\admin\AppData\Local\Temp\ipykernel_8088\591710190.py:1: RuntimeWarning: invalid value encountered in divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
1/0

ZeroDivisionError: division by zero

In [11]:
1/arr # here 1/number it gives place holder of inf(infinity) and warning

C:\Users\admin\AppData\Local\Temp\ipykernel_8088\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
np.sqrt(arr) # square root of every number

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [15]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [16]:
np.log(arr)

C:\Users\admin\AppData\Local\Temp\ipykernel_8088\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [17]:
arr.sum() # sum of all elements 

55

In [18]:
arr.max # max element among array

10

In [19]:
arr.min() # min value element among  array

0

In [20]:
arr.mean() # mean of array

5.0

In [21]:
arr.var() # variation in array

10.0

In [22]:
arr.std()   # stander deveation of array

3.1622776601683795

In [24]:
 arr2 = np.arange(0,16).reshape(4,4) # Creating a 2d array

In [25]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
arr2.shape

(4, 4)

In [27]:
arr2.sum()

120

In [28]:
arr2.sum(axis=0) # perfoerm operation along the rows

array([24, 28, 32, 36])

In [29]:
arr2.sum(axis=1) # perform operatinon along columns

array([ 6, 22, 38, 54])