In [1]:
import numpy as np # importing numpy

In [2]:
# creating a numpy array

In [3]:
#directly transform python array into numpy array

In [4]:
list = [1,2,3]

In [5]:
type(list)

list

In [6]:
np.array(list)# it is function to conevert the normal array into numpy array 

array([1, 2, 3])

In [7]:
list  # here the origianl list is not affected 

[1, 2, 3]

In [8]:
myarr = np.array(list) # we have to asign a variable to that to create a numpy arrat

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [18]:
matrix =[[1,2,3],[4,5,6],[6,7,8]] # here is two dimenional list

In [19]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [21]:
np.array(matrix)# numpy itself detect the list is two dimmestional so 

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
#built in methods and function in numpy

In [28]:
#np.arange(start,stop,optional step size) 
# it generate the data set 


In [29]:
np.arange(0,10,2) #here it start from 0 and goes upto 10 but not including 10 by step size 2

array([0, 2, 4, 6, 8])

In [30]:
np.arange(0,12) # here we dont give step size

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
#it is comman to create large array of zeros and ones so we use
# np.zero(no.of zero)

In [33]:
np.zeros(5) # it generate the 0 in  form on floatinf point number

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3))# (rows,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
#np.ones(no.of ones)

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
#linspace functionb
#np.linspace(start,zero,no.between start and zero)

In [44]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [45]:
np.linspace(0,1,23)

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       , 0.54545455, 0.59090909, 0.63636364,
       0.68181818, 0.72727273, 0.77272727, 0.81818182, 0.86363636,
       0.90909091, 0.95454545, 1.        ])

In [47]:
len(np.linspace(0,12,32))

32

In [49]:
# eye function
# used to create identity matrix
# np.eye(no of rows & columns)

In [50]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [51]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [52]:
# how to create random dirstirbution of data

In [53]:
#numpy comes with its own random library 
# here are some random function on numpy

In [55]:
#1. np.random.rand (no.of rows,&no.of columns) 
#reate an array of the givenn shape and populate it with random samples from a uniform distribution over ``[0, 1)``

In [56]:
np.random.rand(1)

array([0.05986976])

In [60]:
np.random.rand(9,2)

array([[0.44272954, 0.08355979],
       [0.30383634, 0.68095782],
       [0.65265727, 0.68413008],
       [0.09362513, 0.83101677],
       [0.40251891, 0.31128203],
       [0.30755569, 0.1237275 ],
       [0.16596916, 0.95503199],
       [0.68225562, 0.05594923],
       [0.53184222, 0.31140182]])

In [61]:
#2.np.random.randn()
#Return a sample (or samples) from the "standard normal" distribution.

In [62]:
np.random.randn(10)

array([-1.67197482,  1.01044709, -0.92936548,  0.14943222,  2.01374532,
       -1.1786555 ,  0.43020008, -0.28851952,  0.34557496, -1.88479485])

In [63]:
np.random.randn(3,6)

array([[ 0.21744037,  0.07896598, -0.40756499,  0.74036289, -0.57225524,
        -0.03296039],
       [-0.76707938, -1.50238662, -0.47260232,  1.06601731,  0.64686738,
        -1.66473429],
       [ 0.57173482,  3.33406584,  1.07234803,  0.38326126, -1.77497534,
        -0.46991129]])

In [64]:
#3.np.random.randint (low,high,(no.of rows&columns))
#Reutrn only integers 

In [67]:
np.random.randint(3,4,5)

array([3, 3, 3, 3, 3])

In [69]:
np.random.randint(0,45,(3,4))

array([[30, 25,  6, 33],
       [13, 22,  1, 39],
       [42,  6,  0,  5]])

In [70]:
np.random.randint(23,45,10)

array([31, 24, 30, 39, 30, 25, 29, 25, 42, 31])

In [71]:
#4.np.random.seed 
# allow use to set a perticula sets of random numbers 
#if  we set seed for then it give random value 

In [72]:
np.random.seed(45)
np.random.rand(6)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ,
       0.47280797])

In [73]:
np.random.seed(45)
np.random.rand(6)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ,
       0.47280797])

In [74]:
np.random.seed(45)
np.random.rand(3)

array([0.98901151, 0.54954473, 0.2814473 ])

In [75]:
ar= np.arange(0,25)

In [76]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
# here multiple of  no.of rows and column is equal to no. of orginal arr

In [80]:
ar.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [81]:
ranarr = np.random.randint(0,101,10) # creating a random array

In [82]:
ranarr

array([61, 85, 35, 68, 15, 65, 14, 53, 57, 72])

In [83]:
ranarr.max() # find max element in array

85

In [84]:
ranarr.min()# find min element 

14

In [87]:
ranarr.argmax() # give index of max element

1

In [88]:
ranarr.argmin()# give index of min element

6

In [91]:
ranarr.dtype # data type of array

dtype('int32')

In [92]:
ranarr.shape# gives no of rows and column

(10,)

In [99]:
num=ranarr.reshape(2,5)

In [101]:
num.shape

(2, 5)