In [1]:
import numpy as np

In [2]:
arr =np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8] # indexing in one dimession

8

In [7]:
arr[1:5] 

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#BRODCASTING

In [15]:
arr[:5] =  100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
arr =np.arange(0,11)

In [27]:
slic_arr = arr[0:5] # only act as a poninter to original array

In [29]:
slic_arr


array([0, 1, 2, 3, 4])

In [30]:
arr   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slic_arr[:] =78# if we change in slic of array then original array is also effected

In [32]:
arr

array([78, 78, 78, 78, 78,  5,  6,  7,  8,  9, 10])

In [33]:
slic_arr

array([78, 78, 78, 78, 78])

In [34]:
arr_copy = arr.copy()# to not effect the origianl array we use .copy() method to create a copy of array:

In [35]:
arr_copy

array([78, 78, 78, 78, 78,  5,  6,  7,  8,  9, 10])

In [36]:
arr_copy[:8]=99

In [37]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10])

In [40]:
arr2= np.array([[34,23,64],[24,53,21],[26,30,39]])

In [41]:
arr2

array([[34, 23, 64],
       [24, 53, 21],
       [26, 30, 39]])

In [43]:
arr2.shape

(3, 3)

In [44]:
arr2[0]

array([34, 23, 64])

In [45]:
arr2[-1]

array([26, 30, 39])

In [46]:
arr2[0][2]

64

In [47]:
arr2[0,2]

64

In [48]:
arr2[2,1]

30

In [49]:
arr2[:2]

array([[34, 23, 64],
       [24, 53, 21]])

In [50]:
arr2[:2,1:]

array([[23, 64],
       [53, 21]])

In [51]:
#CONDITONAL SELECTION

In [52]:
arr = np.arange(90,101)

In [53]:
arr

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [55]:
arr>94

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [56]:
bool_arr = arr>95

In [57]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [58]:
arr[bool_arr]

array([ 96,  97,  98,  99, 100])

In [59]:
arr[arr>92]

array([ 93,  94,  95,  96,  97,  98,  99, 100])